# hometask 02 part1
Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Create VM - 1"
  config.vm.box = "./generic/debian11"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.name = "task2_1.vagrant.vm"
    # Customize the amount of memory on the VM:
    vb.memory = "512"
  end

  config.vm.synced_folder "./files", "/vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2 php libapache2-mod-php
    systemctl enable apache2
    echo 'Listen 8081' >> /etc/apache2/ports.conf
    systemctl restart apache2
    mkdir /var/www/html/php/
    cp /vagrant/index.html /var/www/html/
    cp /vagrant/index.php /var/www/html/php/
    cp /vagrant/php-site.conf /etc/apache2/sites-available/
    a2ensite php-site.conf
    service apache2 restart
  SHELL

end