---
- name: Slave-01 playbook
  hosts: slave-01
  become: true

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Reload Apache
      service:
        name: apache2
        state: reloaded