# hometask - 02 part2
Vagrant.configure("2") do |config|

  # VM1
  config.vm.define "static" do |static|
    static.vm.box = "./generic/debian11"
    static.vm.network "private_network", ip: "192.168.33.10"
    static.vm.synced_folder "./files", "/vagrant"

    static.vm.provider "virtualbox" do |vb|
      vb.name = "task2-2-static"
      # Customize the amount of memory on the VM:
      vb.memory = "512"
    end

    static.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2 php libapache2-mod-php
      systemctl enable apache2
      cp /vagrant/index.html /var/www/html/
      systemctl restart apache2
    SHELL
  end

  # VM2
  config.vm.define "dynamic" do |dynamic|
    dynamic.vm.box = "./generic/debian11"
    dynamic.vm.network "private_network", ip: "192.168.33.11"
    dynamic.vm.synced_folder "./files", "/vagrant"

    dynamic.vm.provider "virtualbox" do |vb|
      vb.name = "task2-2-dynamic"
      # Customize the amount of memory on the VM:
      vb.memory = "512"
    end

    dynamic.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2 php libapache2-mod-php
    systemctl enable apache2
    mkdir /var/www/html/php/
    cp /vagrant/index.html /var/www/html/php
    cp /vagrant/php-site.conf /etc/apache2/sites-available/
    a2ensite php-site.conf
    systemctl restart apache2
    SHELL
  end
end